#define RETRO_TAPPING_PER_KEY
#define QUICK_TAP_TERM 0
#define TAPPING_TERM 170
#define ACHORDION_STREAK
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "EYma6/Ma4qzX"
